import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Camera={camera_id:string;name:string;source:string;source_type:string;location:string;status:string;fps:number;frames_processed:number;error?:string|null};
type Event={event_id:string;camera_id:string;timestamp:string;event_type:string;severity:string;confidence:number;risk_score:number;message:string;zone_name?:string|null;object_type?:string;track_id?:number|null;metadata?:{factors?:string[];dwell_seconds?:number;direction?:string;person_count?:number;drone_track_id?:number}};
type Alert={alert_id:string;event_id:string;camera_id:string;created_at:string;severity:string;title:string;message:string;status:string};
type Zone={zone_id:string;camera_id:string;name:string;zone_type:string;polygon:[number,number][];severity:string;enabled:boolean};
type Mode='WEBCAM'|'UPLOAD'|'RTSP'|'LOCAL';
const API=(import.meta.env.VITE_API_URL||'http://localhost:8000/api/v1').replace(/\/$/,'');
const WS=(import.meta.env.VITE_WS_URL||'ws://localhost:8000').replace(/\/$/,'');
const MAX_CHANNELS=32;

function ZoneEditor({camera,onClose,onSaved}:{camera:Camera;onClose:()=>void;onSaved:()=>void}){
 const canvasRef=useRef<HTMLCanvasElement>(null);const stageRef=useRef<HTMLDivElement>(null);const [points,setPoints]=useState<[number,number][]>([]);const [zoneName,setZoneName]=useState('Restricted Border Area');const [zoneType,setZoneType]=useState('RESTRICTED');const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{const resize=()=>{const c=canvasRef.current,s=stageRef.current;if(!c||!s)return;c.width=s.clientWidth;c.height=s.clientHeight;draw()};const draw=()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,c.width,c.height);if(points.length){ctx.beginPath();points.forEach((p,i)=>{const x=p[0]*c.width,y=p[1]*c.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});if(points.length>2)ctx.closePath();ctx.lineWidth=3;ctx.strokeStyle='#ff3030';ctx.fillStyle='rgba(255,30,30,.16)';if(points.length>2)ctx.fill();ctx.stroke();points.forEach(p=>{ctx.beginPath();ctx.arc(p[0]*c.width,p[1]*c.height,5,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#ff3030';ctx.stroke()})}};resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[points]);
 const click=(e:React.MouseEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();setPoints(p=>[...p,[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]])};
 const save=async()=>{if(points.length<3){setError('Draw at least 3 points.');return}setSaving(true);setError('');try{const r=await fetch(`${API}/zones`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({camera_id:camera.camera_id,name:zoneName.trim()||'Restricted Zone',zone_type:zoneType,polygon:points,severity:'HIGH',enabled:true})});if(!r.ok)throw Error(await r.text());onSaved();onClose()}catch(e){setError(`Could not save zone: ${e instanceof Error?e.message:'Unknown error'}`)}finally{setSaving(false)}};
 return <div className="zoneOverlay"><div className="zoneEditor"><div className="zoneHeader"><div><b>ZONE CONFIGURATION</b><small>{camera.name} · {camera.location||'Unassigned location'}</small></div><button onClick={onClose}>×</button></div><div ref={stageRef} className="zoneStage"><img src={`${API}/cameras/${camera.camera_id}/stream`} alt="Camera feed for zone drawing"/><canvas ref={canvasRef} onClick={click}/><div className="zoneHelp">Click the video to place polygon points</div></div><div className="zoneControls"><input value={zoneName} onChange={e=>setZoneName(e.target.value)} placeholder="Zone name"/><select value={zoneType} onChange={e=>setZoneType(e.target.value)}><option value="RESTRICTED">Restricted</option><option value="MONITORED">Monitored</option><option value="EXCLUSION">Exclusion</option></select><span>{points.length} points</span><button onClick={()=>setPoints([])}>CLEAR</button><button className="primary" disabled={saving} onClick={save}>{saving?'SAVING...':'SAVE ZONE'}</button></div>{error&&<div className="zoneError">{error}</div>}</div></div>
}

function App(){
 const [cameras,setCameras]=useState<Camera[]>([]),[events,setEvents]=useState<Event[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[summary,setSummary]=useState<any>({});
 const [name,setName]=useState('Border Camera'),[location,setLocation]=useState('North Gate'),[source,setSource]=useState('0'),[mode,setMode]=useState<Mode>('WEBCAM');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const [selectedCamera,setSelectedCamera]=useState<string|null>(null);const [zoneCamera,setZoneCamera]=useState<Camera|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 const load=async()=>{try{const [c,e,a,s]=await Promise.all([fetch(`${API}/cameras`),fetch(`${API}/events?limit=25`),fetch(`${API}/alerts?limit=15`),fetch(`${API}/analytics/summary`)]);if(!c.ok||!e.ok||!a.ok||!s.ok)throw Error('Backend request failed');setCameras(await c.json());setEvents(await e.json());setAlerts(await a.json());setSummary(await s.json())}catch{setMessage(`Cannot reach SRT backend at ${API}. Check that FastAPI is running on port 8000.`)}};
 useEffect(()=>{load();const t=setInterval(load,2500);return()=>clearInterval(t)},[]);useEffect(()=>{let ws:WebSocket|undefined;try{ws=new WebSocket(`${WS}/ws/events`);ws.onmessage=()=>load();ws.onerror=()=>{}}catch{}return()=>ws?.close()},[]);
 const selectMode=(m:Mode)=>{setMode(m);setMessage('');if(m==='WEBCAM')setSource('0');else if(m!=='RTSP')setSource('')};
 const upload=async(f:File)=>{setBusy(true);setMessage(`Uploading ${f.name}...`);try{const fd=new FormData();fd.append('file',f);const r=await fetch(`${API}/uploads/video`,{method:'POST',body:fd});if(!r.ok)throw Error(await r.text());const x=await r.json();if(!x.source)throw Error('Upload succeeded but backend returned no source path');setSource(x.source);setMode('UPLOAD');setMessage(`Uploaded: ${f.name}. Click + ADD SOURCE to add it to SRT.`)}catch(err){setMessage(`Video upload failed: ${err instanceof Error?err.message:'Unknown error'}`)}finally{setBusy(false)}};
 const add=async()=>{if(cameras.length>=MAX_CHANNELS){setMessage(`Maximum ${MAX_CHANNELS} channels are already configured.`);return}if(!source.trim()){setMessage('Enter a source or select a video first.');return}setBusy(true);setMessage('Adding camera source...');try{const r=await fetch(`${API}/cameras`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim()||`SRT Camera ${cameras.length+1}`,source:source.trim(),location:location.trim(),enabled:true})});if(!r.ok)throw Error(await r.text());const camera=await r.json();setMessage(`${camera.name} added successfully. Click START on its channel.`);if(mode!=='RTSP')setSource(mode==='WEBCAM'?'0':'');await load()}catch(err){setMessage(`Could not add source: ${err instanceof Error?err.message:'Unknown error'}`)}finally{setBusy(false)}};
 const act=async(id:string,a:'start'|'stop')=>{setBusy(true);setMessage(`${a==='start'?'Starting':'Stopping'} camera...`);try{const r=await fetch(`${API}/cameras/${id}/${a}`,{method:'POST'});if(!r.ok)throw Error(await r.text());await load()}catch(err){setMessage(`Camera ${a} failed: ${err instanceof Error?err.message:'Unknown error'}`)}finally{setBusy(false)}};
 const remove=async(c:Camera)=>{if(!window.confirm(`Remove ${c.name} from the channel grid?`))return;setBusy(true);setMessage(`Removing ${c.name}...`);try{const r=await fetch(`${API}/cameras/${c.camera_id}`,{method:'DELETE'});if(!r.ok)throw Error(await r.text());if(selectedCamera===c.camera_id)setSelectedCamera(null);setMessage(`${c.name} removed.`);await load()}catch(err){setMessage(`Remove failed: ${err instanceof Error?err.message:'Unknown error'}`)}finally{setBusy(false)}};
 const fullscreen=(id:string)=>{const el=document.getElementById(`camera-${id}`);if(!el)return;if(document.fullscreenElement){document.exitFullscreen().catch(()=>{});return}el.requestFullscreen?.().catch(()=>setMessage('Fullscreen is not available in this browser.'))};
 const alertStatus=async(id:string,status:string)=>{try{const r=await fetch(`${API}/alerts/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(!r.ok)throw Error(await r.text());await load()}catch(err){setMessage(`Alert update failed: ${err instanceof Error?err.message:'Unknown error'}`)}};
 return <div className="app"><header><div><div className="eyebrow">PROJECT SRT // COMMAND CENTER</div><h1>Smart Recognition & Tracking</h1><p>AI video analytics for existing CCTV infrastructure</p></div><div className="live"><i/> SYSTEM ONLINE</div></header>
 {message&&<div className="notice" role="status">{message}<button aria-label="Dismiss message" onClick={()=>setMessage('')}>×</button></div>}
 <section className="metrics"><Metric label="CAMERAS ONLINE" value={`${summary.cameras_online??0}/${summary.cameras_total??cameras.length}`}/><Metric label="EVENTS" value={summary.events_total??events.length}/><Metric label="HIGH RISK" value={summary.high_priority??0}/><Metric label="PIPELINE" value="Live"/></section>
 <main><section className="panel setup"><div className="paneltitle"><span>INPUT SOURCES</span><small>CONNECT / EVALUATE</small></div><div className="modes">{(['WEBCAM','UPLOAD','RTSP','LOCAL'] as const).map(m=><button key={m} className={mode===m?'active':''} onClick={()=>selectMode(m)}>{m==='WEBCAM'?'WEBCAM':m==='UPLOAD'?'VIDEO FILE':m==='RTSP'?'IP / RTSP':'LOCAL PATH'}</button>)}</div><div className="formrow"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Camera name"/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location"/></div><div className="sourceRow">{mode==='UPLOAD'?<><input ref={fileRef} type="file" accept="video/mp4,video/avi,video/quicktime,video/x-matroska,video/webm" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/><button className="primary" disabled={busy||cameras.length>=MAX_CHANNELS} onClick={()=>fileRef.current?.click()}>{busy?'UPLOADING...':'SELECT SAMPLE VIDEO'}</button></>:<input value={source} onChange={e=>setSource(e.target.value)} placeholder={mode==='WEBCAM'?'Webcam index: 0':mode==='RTSP'?'rtsp://user:password@camera/stream':'C:/path/to/video.mp4'}/>}<button className="add" disabled={busy||!source.trim()||cameras.length>=MAX_CHANNELS} onClick={add}>+ ADD SOURCE</button></div><div className="setupHint"><span>{cameras.length}/{MAX_CHANNELS} channels configured</span><span>{mode==='WEBCAM'?'Local webcam input':mode==='UPLOAD'?'Upload and evaluate recorded video':mode==='RTSP'?'Connect an IP camera / NVR stream':'Evaluate a local video path'}</span></div></section>
 <section className="panel cameras"><div className="paneltitle"><span>LIVE CAMERAS</span><small>{cameras.length}/{MAX_CHANNELS} CHANNELS · {cameras.filter(c=>c.status==='ONLINE').length} ONLINE</small></div>{cameras.length===0?<div className="empty">Add a webcam, uploaded video, local file or RTSP/IP camera to begin.</div>:<div className="grid">{cameras.slice(0,MAX_CHANNELS).map(c=><article id={`camera-${c.camera_id}`} key={c.camera_id} className={`camera ${selectedCamera===c.camera_id?'selected':''}`}><div className="feed" onClick={()=>setSelectedCamera(c.camera_id)}>{c.status==='ONLINE'?<img src={`${API}/cameras/${c.camera_id}/stream`} alt={`${c.name} live stream`}/>:<div className="offline">{c.status}<br/><small>{c.error||'Start processing to open stream'}</small></div>}<span className="tag">{c.source_type}</span><span className={`statusBadge ${c.status==='ONLINE'?'online':''}`}>{c.status}</span><button className="fullscreen" title="Open full screen (Esc to exit)" aria-label={`Fullscreen ${c.name}`} onClick={e=>{e.stopPropagation();fullscreen(c.camera_id)}}>⛶</button></div><div className="caminfo"><div><b>{c.name}</b><small>{c.location||'Unassigned location'}</small></div></div><div className="controls"><span>{c.fps.toFixed(1)} FPS · {c.frames_processed} frames</span><div><button disabled={busy} onClick={()=>act(c.camera_id,c.status==='ONLINE'?'stop':'start')}>{c.status==='ONLINE'?'STOP':'START'}</button><button className="zoneBtn" disabled={busy||c.status!=='ONLINE'} onClick={()=>setZoneCamera(c)}>ZONE</button><button className="remove" disabled={busy} onClick={()=>remove(c)}>REMOVE</button></div></div></article>)}</div>}</section>
 <section className="panel events"><div className="paneltitle"><span>EVENT INTELLIGENCE</span><small>REAL-TIME FEED</small></div>{events.length===0?<div className="empty">No events yet. Draw a restricted zone and start a camera to activate intrusion reasoning.</div>:events.map(e=><div key={e.event_id} className={`event ${e.severity.toLowerCase()}`}><div className="dot"/><div className="eventmain"><b>{e.event_type} · {e.message}</b><small>{new Date(e.timestamp).toLocaleString()} · Track #{e.track_id??'—'} · {e.zone_name||'No zone'}{e.metadata?.dwell_seconds!==undefined?` · Dwell ${Math.round(e.metadata.dwell_seconds)}s`:''}{e.metadata?.direction?` · ${e.metadata.direction}`:''}{e.metadata?.person_count?` · ${e.metadata.person_count} persons`:''}{e.metadata?.drone_track_id?` · Drone #${e.metadata.drone_track_id}`:''}</small>{e.metadata?.factors?.length?<div className="factors">{e.metadata.factors.map(f=><span key={f}>{f}</span>)}</div>:null}</div><strong>{e.risk_score}</strong></div>)}</section>
 <section className="panel events"><div className="paneltitle"><span>ALERT QUEUE</span><small>OPERATOR ACTION</small></div>{alerts.length===0?<div className="empty">No active alerts.</div>:alerts.map(a=><div key={a.alert_id} className={`event ${a.severity.toLowerCase()}`}><div className="dot"/><div className="eventmain"><b>{a.title}</b><small>{a.message} · {new Date(a.created_at).toLocaleString()}</small></div><span className="state">{a.status}</span>{a.status==='NEW'&&<button onClick={()=>alertStatus(a.alert_id,'ACKNOWLEDGED')}>ACK</button>}</div>)}</section></main><footer>PROJECT SRT · OPERATOR ASSISTANCE SYSTEM · {cameras.length}/{MAX_CHANNELS} CHANNELS</footer>{zoneCamera&&<ZoneEditor camera={zoneCamera} onClose={()=>setZoneCamera(null)} onSaved={()=>{setMessage('Zone saved. Intrusion reasoning is now active for this camera.');load()}}/>}</div>}
function Metric({label,value}:{label:string,value:any}){return <div className="metric"><small>{label}</small><b>{value}</b></div>}
createRoot(document.getElementById('root')!).render(<App/>);
