import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Camera={camera_id:string;name:string;source:string;source_type:string;location:string;status:string;fps:number;frames_processed:number;error?:string|null};
type Event={event_id:string;camera_id:string;timestamp:string;event_type:string;severity:string;confidence:number;risk_score:number;message:string;zone_name?:string|null;object_type?:string;track_id?:number|null;evidence_frame?:string|null;metadata?:any};
type Alert={alert_id:string;event_id:string;camera_id:string;created_at:string;severity:string;title:string;message:string;status:string};
type Mode='WEBCAM'|'UPLOAD'|'RTSP'|'LOCAL';
const API=(import.meta.env.VITE_API_URL||'http://localhost:8000/api/v1').replace(/\/$/,''); const MAX=64;
function App(){
 const [cameras,setCameras]=useState<Camera[]>([]),[events,setEvents]=useState<Event[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[summary,setSummary]=useState<any>({}),[anpr,setAnpr]=useState<any[]>([]);
 const [name,setName]=useState('Border Camera'),[location,setLocation]=useState('North Gate'),[source,setSource]=useState('0'),[mode,setMode]=useState<Mode>('WEBCAM');
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState<Event[]>([]),[critical,setCritical]=useState<Alert|null>(null),[selected,setSelected]=useState<Event|null>(null); const fileRef=useRef<HTMLInputElement>(null); const seen=useRef(new Set<string>()),init=useRef(false),audio=useRef<AudioContext|null>(null);
 const unlock=()=>{try{const C=window.AudioContext||(window as any).webkitAudioContext; if(C){audio.current=audio.current||new C();if(audio.current.state==='suspended')void audio.current.resume()}}catch{}};
 const alarm=(a:Alert)=>{unlock();try{const c=audio.current;if(c){const n=c.currentTime;[0,.18,.36].forEach(o=>{const x=c.createOscillator(),g=c.createGain();x.frequency.value=880;g.gain.setValueAtTime(.001,n+o);g.gain.exponentialRampToValueAtTime(.22,n+o+.02);g.gain.exponentialRampToValueAtTime(.001,n+o+.14);x.connect(g);g.connect(c.destination);x.start(n+o);x.stop(n+o+.16)})}}catch{}try{speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`Alert. Alert. ${a.title}. ${a.message}`))}catch{}};
 const load=async()=>{try{const rs=await Promise.all([fetch(`${API}/cameras`),fetch(`${API}/events?limit=40`),fetch(`${API}/alerts?limit=30`),fetch(`${API}/analytics/summary`),fetch(`${API}/anpr/summary`)]);if(rs.some(r=>!r.ok))throw Error();const [c,e,a,s,p]=await Promise.all(rs.map(r=>r.json()));setCameras(c);setEvents(e);setAlerts(a);setSummary(s);setAnpr(p.results||[]);if(!init.current){a.forEach((x:Alert)=>seen.current.add(x.alert_id));init.current=true}else{const u=a.find((x:Alert)=>(x.severity==='HIGH'||x.severity==='CRITICAL')&&x.status==='NEW'&&!seen.current.has(x.alert_id));a.forEach((x:Alert)=>seen.current.add(x.alert_id));if(u){setCritical(u);alarm(u);setTimeout(()=>setCritical(v=>v?.alert_id===u.alert_id?null:v),8000)}}}catch{setNotice(`Backend unavailable — ${API}`)}};
 useEffect(()=>{load();const t=setInterval(load,2500);return()=>clearInterval(t)},[]);
 const all=async(a:'start'|'stop')=>{unlock();const t=a==='start'?cameras.filter(c=>c.enabled&&c.status!=='ONLINE'):cameras.filter(c=>c.status==='ONLINE'||c.status==='CONNECTING');setBusy(true);setNotice(`${a==='start'?'Starting':'Stopping'} ${t.length} cameras simultaneously...`);await Promise.allSettled(t.map(c=>fetch(`${API}/cameras/${c.camera_id}/${a}`,{method:'POST'})));await load();setBusy(false)};
 const act=async(id:string,a:'start'|'stop')=>{setBusy(true);await fetch(`${API}/cameras/${id}/${a}`,{method:'POST'});await load();setBusy(false)};
 const add=async()=>{if(!source.trim())return setNotice('Enter a source first.');setBusy(true);try{const r=await fetch(`${API}/cameras`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name||`SRT Camera ${cameras.length+1}`,source:source.trim(),location,enabled:true})});if(!r.ok)throw Error(await r.text());setNotice('Camera added.');await load()}catch(e){setNotice(String(e))}finally{setBusy(false)}};
 const upload=async(f:File)=>{setBusy(true);try{const fd=new FormData();fd.append('file',f);const r=await fetch(`${API}/uploads/video`,{method:'POST',body:fd});const x=await r.json();if(!r.ok)throw Error(x.detail||'Upload failed');setSource(x.source);setMode('LOCAL');setNotice('Video uploaded — click ADD SOURCE.')}catch(e){setNotice(String(e))}finally{setBusy(false)}};
 const remove=async(id:string)=>{if(confirm('Remove this camera?')){await fetch(`${API}/cameras/${id}`,{method:'DELETE'});await load()}};
 const ack=async(a:Alert)=>{await fetch(`${API}/alerts/${a.alert_id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'ACKNOWLEDGED'})});await load()}; const delAlert=async(a:Alert)=>{await fetch(`${API}/alerts/${a.alert_id}`,{method:'DELETE'});await load()}; const delEvent=async(e:Event)=>{await fetch(`${API}/events/${e.event_id}`,{method:'DELETE'});setSelected(null);await load()};
 const search=async()=>{if(!query.trim())return;try{const r=await fetch(`${API}/search?q=${encodeURIComponent(query)}&limit=100`);const x=await r.json();setResults(x.results||[]);setNotice(`${x.results?.length||0} matching events`) }catch{setNotice('Search failed')}};
 const online=cameras.filter(c=>c.status==='ONLINE').length;
 return <div className="app"><header><div><div className="eyebrow">PROJECT SRT // COMMAND CENTER</div><h1>Smart Recognition & Tracking</h1><p>AI video analytics for existing CCTV / NVR infrastructure</p></div><div className="headerRight"><div className="globalControls"><button className="globalStop" disabled={busy||!online} onClick={()=>all('stop')}>■ STOP ALL</button><button className="globalStart" disabled={busy||!cameras.length} onClick={()=>all('start')}>▶ START ALL</button></div><div className="live"><i/> SYSTEM ONLINE</div></div></header>
 {critical&&<div className="criticalBanner"><div><strong>⚠ ALERT — ALERT</strong><span>{critical.title}: {critical.message}</span></div><button onClick={()=>setCritical(null)}>×</button></div>}{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 <section className="metrics"><Metric label="CAMERAS ONLINE" value={`${online}/${cameras.length}`}/><Metric label="EVENTS" value={summary.events_total??events.length}/><Metric label="HIGH RISK" value={summary.high_priority??0}/><Metric label="PLATES READ" value={anpr.filter(x=>x.plate_text).length}/></section>
 <main><section className="panel setup"><div className="paneltitle"><span>INPUT SOURCES</span><small>{cameras.length}/{MAX} CHANNELS</small></div><div className="modes">{(['WEBCAM','UPLOAD','RTSP','LOCAL'] as Mode[]).map(m=><button key={m} className={mode===m?'active':''} onClick={()=>{setMode(m);if(m==='WEBCAM')setSource('0');else setSource('')}}>{m==='UPLOAD'?'VIDEO FILE':m==='RTSP'?'IP / RTSP':m}</button>)}</div><div className="formrow"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Camera name"/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location / sector"/></div><div className="sourceRow">{mode==='UPLOAD'?<><input ref={fileRef} type="file" accept="video/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/><button className="primary" onClick={()=>fileRef.current?.click()}>SELECT VIDEO</button></>:<input value={source} onChange={e=>setSource(e.target.value)} placeholder={mode==='RTSP'?'rtsp://user:password@camera/stream':mode==='WEBCAM'?'0':'C:/path/video.mp4'}/>}<button className="add" disabled={busy||cameras.length>=MAX} onClick={add}>+ ADD SOURCE</button></div></section>
 <section className="panel cameras"><div className="paneltitle"><span>LIVE CAMERAS</span><small>{online} ONLINE</small></div>{!cameras.length?<div className="empty">Add a webcam, video or RTSP/IP camera to begin.</div>:<div className="grid">{cameras.slice(0,MAX).map(c=><article className="camera" key={c.camera_id}><div className="feed"><img src={`${API}/cameras/${c.camera_id}/stream`} alt={c.name}/><span className="statusBadge">{c.status}</span></div><div className="caminfo"><b>{c.name}</b><small>{c.location} · {c.fps?.toFixed?.(1)||0} FPS · {c.frames_processed||0} frames</small></div><div className="controls"><span>{c.source_type}</span><div><button onClick={()=>act(c.camera_id,c.status==='ONLINE'?'stop':'start')}>{c.status==='ONLINE'?'STOP':'START'}</button><button className="remove" onClick={()=>remove(c.camera_id)}>×</button></div></div></article>)}</div>}</section>
 <section className="panel"><div className="paneltitle"><span>NATURAL-LANGUAGE INTELLIGENCE</span><small>SEARCH EVENT MEMORY</small></div><div className="sourceRow"><input className="nlInput" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Try: show night time movements in camera 1"/><button className="primary" onClick={search}>SEARCH</button></div><div className="chips"><button onClick={()=>{setQuery('night movement');setTimeout(search,0)}}>Night movement</button><button onClick={()=>{setQuery('restricted intrusion');setTimeout(search,0)}}>Restricted intrusion</button><button onClick={()=>{setQuery('high risk');setTimeout(search,0)}}>High risk</button><button onClick={()=>{setQuery('multiple people');setTimeout(search,0)}}>Group activity</button></div><div>{(results.length?results:events.slice(0,8)).map(e=><div className="event" key={e.event_id} onClick={()=>setSelected(e)}><span className="dot"/><div className="eventmain"><b>{e.event_type.replaceAll('_',' ')}</b><small>{e.message} · {e.camera_id} · {new Date(e.timestamp).toLocaleTimeString()}</small>{e.metadata?.factors&&<div className="factors">{e.metadata.factors.map((f:string)=><span key={f}>{f}</span>)}</div>}</div><strong>{e.risk_score}</strong><button onClick={x=>{x.stopPropagation();delEvent(e)}}>×</button></div>)}</div></section>
 <div className="two"><section className="panel"><div className="paneltitle"><span>ALERT QUEUE</span><small>ACKNOWLEDGE / CLEAR</small></div>{alerts.length?alerts.map(a=><div className="event" key={a.alert_id}><span className="dot"/><div className="eventmain"><b>{a.title}</b><small>{a.message} · {a.camera_id}</small></div>{a.status==='NEW'&&<button onClick={()=>ack(a)}>✓</button>}<button onClick={()=>delAlert(a)}>×</button></div>):<div className="empty">No active alerts.</div>}</section>
 <section className="panel"><div className="paneltitle"><span>ANPR / VEHICLE INTELLIGENCE</span><small>LIVE</small></div>{anpr.length?anpr.slice(-15).reverse().map((p,i)=><div className="event" key={i}><span className="plate">{p.plate_text||'PLATE CANDIDATE'}</span><div className="eventmain"><b>{p.vehicle_type}</b><small>{p.status} · {Math.round((p.confidence||0)*100)}% confidence</small></div></div>):<div className="empty">Vehicle detection is active. Readable plates appear when OCR can confidently recover text.</div>}</section></div>
 <div className="two"><section className="panel"><div className="paneltitle"><span>EVENT HISTORY</span><small>OPERATOR MEMORY</small></div>{events.slice(0,15).map(e=><div className="event" key={e.event_id}><span className="dot"/><div className="eventmain" onClick={()=>setSelected(e)}><b>{e.event_type.replaceAll('_',' ')}</b><small>{e.message}</small></div><button onClick={()=>delEvent(e)}>×</button></div>)}</section><section className="panel"><div className="paneltitle"><span>CAPABILITIES</span><small>SRT INTELLIGENCE STACK</small></div><div className="capabilities"><span>✓ Person detection & tracking</span><span>✓ Restricted-zone intrusion</span><span>✓ Night movement analysis</span><span>✓ Loitering / dwell analysis</span><span>✓ Group activity detection</span><span>✓ Explainable risk scoring</span><span>✓ ANPR + OCR layer</span><span>✓ Natural-language event search</span><span>✓ Evidence snapshots</span><span>✓ RTSP / IP camera input</span><span>✓ Multi-camera concurrent processing</span><span>✓ Operator alert acknowledgement</span></div></section></div>
 </main>{selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="evidence" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><h2>{selected.event_type.replaceAll('_',' ')}</h2><p>{selected.message}</p><div className="evidenceGrid"><div><b>Camera</b><span>{selected.camera_id}</span></div><div><b>Risk</b><span>{selected.risk_score}/100</span></div><div><b>Confidence</b><span>{Math.round(selected.confidence*100)}%</span></div><div><b>Object</b><span>{selected.object_type||'—'} {selected.track_id?`#${selected.track_id}`:''}</span></div></div>{selected.evidence_frame?<img src={`${API}/events/evidence/${selected.event_id}`} alt="Evidence"/>:<div className="empty">Evidence snapshot unavailable.</div>}</div></div>}</div>}
function Metric({label,value}:{label:string;value:any}){return <div className="metric"><b>{value}</b><small>{label}</small></div>}
createRoot(document.getElementById('root')!).render(<App/>);
